# Site
name: 'Prashant Kapoor'
description: 'Place where I write it down for you, till eternity'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
email: 'prashantkapoor21@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    prashant:
      name:           Prashant
     # site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Prashant, trying to ink my ideas for you to read. I hope you like it!"
      email:          prashantkapoor21@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    harpreet:
      name:           Harpreet
      #site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Full time Developer, part time Blogger, fashionista, love to explore new ideas"
      email:          harpreet.vrd@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: prashant
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]